# Generated by Django 2.2.16 on 2020-09-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200918_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='program_leader',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='program_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='program_sub_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
