# Generated by Django 2.2.16 on 2020-09-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_competence_subcompetence'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='plan',
            field=models.ManyToManyField(to='blog.Plan'),
        ),
        migrations.RemoveField(
            model_name='competence',
            name='subject',
        ),
        migrations.AddField(
            model_name='competence',
            name='subject',
            field=models.ManyToManyField(to='blog.Subject'),
        ),
    ]
